spring:
  application:
    name: boardgame-tracker
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
s3:
  base-s3-url: ""
app:
  security:
    jwt:
      issuer: boardgame-tracker
      access-token-ttl-seconds: 3600
      refresh-token-ttl-seconds: 2592000
      secret: ${JWT_SECRET:change-me-please-change-me-please}
api:
  bgg:
    token: ${BGG_API_TOKEN}
    base-url: https://boardgamegeek.com/xmlapi2
    request-timeout-seconds: 30
    min-delay-millis: 5000
    retry-max-attempts: 5
